create table recon_source_tx (
    source_row_id     number generated by default as identity primary key,
    transaction_ref   varchar2(100) not null,
    transaction_date  date not null,
    amount             number(18,4) not null,
    currency_code      varchar2(3) not null,
    account_ref        varchar2(100),
    created_at         timestamp default systimestamp not null
);

create table recon_target_tx (
    target_row_id     number generated by default as identity primary key,
    transaction_ref   varchar2(100) not null,
    transaction_date  date not null,
    amount             number(18,4) not null,
    currency_code      varchar2(3) not null,
    account_ref        varchar2(100),
    created_at         timestamp default systimestamp not null
);

create table recon_run (
    run_id              number generated by default as identity primary key,
    status              varchar2(20) not null,
    amount_tolerance    number(18,4) default 0 not null,
    started_at          timestamp default systimestamp not null,
    finished_at         timestamp,
    total_results       number default 0 not null,
    matched_count       number default 0 not null,
    mismatch_count      number default 0 not null,
    constraint ck_recon_run_status check(status in ('RUNNING','COMPLETED','FAILED'))
);

create table recon_result (
    result_id           number generated by default as identity primary key,
    run_id              number not null,
    transaction_ref     varchar2(100) not null,
    result_status       varchar2(30) not null,
    source_count        number default 0 not null,
    target_count        number default 0 not null,
    source_amount       number(18,4),
    target_amount       number(18,4),
    amount_difference   number(18,4),
    source_date         date,
    target_date         date,
    source_currency     varchar2(3),
    target_currency     varchar2(3),
    details             varchar2(2000),
    created_at          timestamp default systimestamp not null,
    constraint fk_recon_result_run foreign key(run_id) references recon_run(run_id),
    constraint ck_recon_result_status check (
        result_status in (
            'MATCHED',
            'MISSING_SOURCE',
            'MISSING_TARGET',
            'AMOUNT_MISMATCH',
            'DATE_MISMATCH',
            'CURRENCY_MISMATCH',
            'DUPLICATE_SOURCE',
            'DUPLICATE_TARGET'
        )
    )
);
